# TCL File Generated by Component Editor 23.1
# Thu Nov 14 18:07:24 MST 2024
# DO NOT MODIFY


# 
# mlp_controller "mlp_controller" v1.0
#  2024.11.14.18:07:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mlp_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME mlp_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME mlp_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mlp_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mlp_controller.v VERILOG PATH ../../mlp_controller/mlp_controller.v TOP_LEVEL_FILE
add_fileset_file accum.v VERILOG PATH ../../mlp_controller/accum.v
add_fileset_file axis_mesh.sv SYSTEM_VERILOG PATH ../../mlp_controller/axis_mesh.sv
add_fileset_file axis_passthrough.sv SYSTEM_VERILOG PATH ../../mlp_controller/axis_passthrough.sv
add_fileset_file axis_serdes_shims.sv SYSTEM_VERILOG PATH ../../mlp_controller/axis_serdes_shims.sv
add_fileset_file components.v VERILOG PATH ../../mlp_controller/components.v
add_fileset_file datapath.v VERILOG PATH ../../mlp_controller/datapath.v
add_fileset_file dcfifo_agilex7.sv SYSTEM_VERILOG PATH ../../mlp_controller/dcfifo_agilex7.sv
add_fileset_file dcfifo_mixed_width_agilex7.sv SYSTEM_VERILOG PATH ../../mlp_controller/dcfifo_mixed_width_agilex7.sv
add_fileset_file dpe.v VERILOG PATH ../../mlp_controller/dpe.v
add_fileset_file fifo_agilex7.sv SYSTEM_VERILOG PATH ../../mlp_controller/fifo_agilex7.sv
add_fileset_file mesh.sv SYSTEM_VERILOG PATH ../../mlp_controller/mesh.sv
add_fileset_file mvm_noc.sv SYSTEM_VERILOG PATH ../../mlp_controller/mvm_noc.sv
add_fileset_file noc_pipeline_link.sv SYSTEM_VERILOG PATH ../../mlp_controller/noc_pipeline_link.sv
add_fileset_file parameters.sv SYSTEM_VERILOG PATH ../../mlp_controller/parameters.sv
add_fileset_file reduce.v VERILOG PATH ../../mlp_controller/reduce.v
add_fileset_file reset_synchronizer.sv SYSTEM_VERILOG PATH ../../mlp_controller/reset_synchronizer.sv
add_fileset_file router.sv SYSTEM_VERILOG PATH ../../mlp_controller/router.sv
add_fileset_file rtl_mvm.v VERILOG PATH ../../mlp_controller/rtl_mvm.v


# 
# parameters
# 
add_parameter DATAW INTEGER 128
set_parameter_property DATAW DEFAULT_VALUE 128
set_parameter_property DATAW DISPLAY_NAME DATAW
set_parameter_property DATAW TYPE INTEGER
set_parameter_property DATAW UNITS None
set_parameter_property DATAW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATAW HDL_PARAMETER true
add_parameter IDW INTEGER 4
set_parameter_property IDW DEFAULT_VALUE 4
set_parameter_property IDW DISPLAY_NAME IDW
set_parameter_property IDW TYPE INTEGER
set_parameter_property IDW UNITS None
set_parameter_property IDW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IDW HDL_PARAMETER true
add_parameter DESTW INTEGER 12
set_parameter_property DESTW DEFAULT_VALUE 12
set_parameter_property DESTW DISPLAY_NAME DESTW
set_parameter_property DESTW TYPE INTEGER
set_parameter_property DESTW UNITS None
set_parameter_property DESTW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DESTW HDL_PARAMETER true
add_parameter USERW INTEGER 75
set_parameter_property USERW DEFAULT_VALUE 75
set_parameter_property USERW DISPLAY_NAME USERW
set_parameter_property USERW TYPE INTEGER
set_parameter_property USERW UNITS None
set_parameter_property USERW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USERW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 2
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end led_out leds Output 10

